language: python

python:
  - 2.7

services: postgresql

env:
  - DJANGO=1.10 TEST_DATABASE=sqlite3
  - DJANGO=1.9 TEST_DATABASE=sqlite3
  - DJANGO=1.8 TEST_DATABASE=sqlite3
  - DJANGO=1.10 TEST_DATABASE=postgres
  - DJANGO=1.9 TEST_DATABASE=postgres
  - DJANGO=1.8 TEST_DATABASE=postgres

before_install:
  - export DJANGO_SETTINGS_MODULE=tests.settings
  - export PYTHONPATH=$HOME/builds/Basask/softdelete
  - export PIP_USE_MIRRORS=true

install:
  - pip install -r requirements.txt
  - pip install django==$DJANGO --quiet
  - pip install psycopg2 --quiet

before_script:
  - psql -c "CREATE DATABASE travisci;" -U postgres

script:
  - python runtests.py
